/// This file is generated from generate.py.
/// Re-generate it if you upgrade to a new version of RocksDB.

#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum DBStatisticsTickerType {
    BlockCacheMiss = 0,
    BlockCacheHit = 1,
    BlockCacheAdd = 2,
    BlockCacheAddFailures = 3,
    BlockCacheIndexMiss = 4,
    BlockCacheIndexHit = 5,
    BlockCacheIndexAdd = 6,
    BlockCacheIndexBytesInsert = 7,
    BlockCacheIndexBytesEvict = 8,
    BlockCacheFilterMiss = 9,
    BlockCacheFilterHit = 10,
    BlockCacheFilterAdd = 11,
    BlockCacheFilterBytesInsert = 12,
    BlockCacheFilterBytesEvict = 13,
    BlockCacheDataMiss = 14,
    BlockCacheDataHit = 15,
    BlockCacheDataAdd = 16,
    BlockCacheDataBytesInsert = 17,
    BlockCacheBytesRead = 18,
    BlockCacheBytesWrite = 19,
    BloomFilterUseful = 20,
    BloomFilterFullPositive = 21,
    BloomFilterFullTruePositive = 22,
    BloomFilterMicros = 23,
    PersistentCacheHit = 24,
    PersistentCacheMiss = 25,
    SimBlockCacheHit = 26,
    SimBlockCacheMiss = 27,
    MemtableHit = 28,
    MemtableMiss = 29,
    GetHitL0 = 30,
    GetHitL1 = 31,
    GetHitL2AndUp = 32,
    CompactionKeyDropNewerEntry = 33,
    CompactionKeyDropObsolete = 34,
    CompactionKeyDropRangeDel = 35,
    CompactionKeyDropUser = 36,
    CompactionRangeDelDropObsolete = 37,
    CompactionOptimizedDelDropObsolete = 38,
    CompactionCancelled = 39,
    NumberKeysWritten = 40,
    NumberKeysRead = 41,
    NumberKeysUpdated = 42,
    BytesWritten = 43,
    BytesRead = 44,
    NumberDbSeek = 45,
    NumberDbNext = 46,
    NumberDbPrev = 47,
    NumberDbSeekFound = 48,
    NumberDbNextFound = 49,
    NumberDbPrevFound = 50,
    IterBytesRead = 51,
    NoFileCloses = 52,
    NoFileOpens = 53,
    NoFileErrors = 54,
    StallL0SlowdownMicros = 55,
    StallMemtableCompactionMicros = 56,
    StallL0NumFilesMicros = 57,
    StallMicros = 58,
    DbMutexWaitMicros = 59,
    RateLimitDelayMillis = 60,
    NoIterators = 61,
    NumberMultigetCalls = 62,
    NumberMultigetKeysRead = 63,
    NumberMultigetBytesRead = 64,
    NumberFilteredDeletes = 65,
    NumberMergeFailures = 66,
    BloomFilterPrefixChecked = 67,
    BloomFilterPrefixUseful = 68,
    NumberOfReseeksInIteration = 69,
    GetUpdatesSinceCalls = 70,
    BlockCacheCompressedMiss = 71,
    BlockCacheCompressedHit = 72,
    BlockCacheCompressedAdd = 73,
    BlockCacheCompressedAddFailures = 74,
    WalFileSynced = 75,
    WalFileBytes = 76,
    WriteDoneBySelf = 77,
    WriteDoneByOther = 78,
    WriteTimedout = 79,
    WriteWithWal = 80,
    CompactReadBytes = 81,
    CompactWriteBytes = 82,
    FlushWriteBytes = 83,
    CompactReadBytesMarked = 84,
    CompactReadBytesPeriodic = 85,
    CompactReadBytesTtl = 86,
    CompactWriteBytesMarked = 87,
    CompactWriteBytesPeriodic = 88,
    CompactWriteBytesTtl = 89,
    NumberDirectLoadTableProperties = 90,
    NumberSuperversionAcquires = 91,
    NumberSuperversionReleases = 92,
    NumberSuperversionCleanups = 93,
    NumberBlockCompressed = 94,
    NumberBlockDecompressed = 95,
    NumberBlockNotCompressed = 96,
    MergeOperationTotalTime = 97,
    FilterOperationTotalTime = 98,
    RowCacheHit = 99,
    RowCacheMiss = 100,
    ReadAmpEstimateUsefulBytes = 101,
    ReadAmpTotalReadBytes = 102,
    NumberRateLimiterDrains = 103,
    NumberIterSkip = 104,
    BlobDbNumPut = 105,
    BlobDbNumWrite = 106,
    BlobDbNumGet = 107,
    BlobDbNumMultiget = 108,
    BlobDbNumSeek = 109,
    BlobDbNumNext = 110,
    BlobDbNumPrev = 111,
    BlobDbNumKeysWritten = 112,
    BlobDbNumKeysRead = 113,
    BlobDbBytesWritten = 114,
    BlobDbBytesRead = 115,
    BlobDbWriteInlined = 116,
    BlobDbWriteInlinedTtl = 117,
    BlobDbWriteBlob = 118,
    BlobDbWriteBlobTtl = 119,
    BlobDbBlobFileBytesWritten = 120,
    BlobDbBlobFileBytesRead = 121,
    BlobDbBlobFileSynced = 122,
    BlobDbBlobIndexExpiredCount = 123,
    BlobDbBlobIndexExpiredSize = 124,
    BlobDbBlobIndexEvictedCount = 125,
    BlobDbBlobIndexEvictedSize = 126,
    BlobDbGcNumFiles = 127,
    BlobDbGcNumNewFiles = 128,
    BlobDbGcFailures = 129,
    BlobDbGcNumKeysOverwritten = 130,
    BlobDbGcNumKeysExpired = 131,
    BlobDbGcNumKeysRelocated = 132,
    BlobDbGcBytesOverwritten = 133,
    BlobDbGcBytesExpired = 134,
    BlobDbGcBytesRelocated = 135,
    BlobDbFifoNumFilesEvicted = 136,
    BlobDbFifoNumKeysEvicted = 137,
    BlobDbFifoBytesEvicted = 138,
    TxnPrepareMutexOverhead = 139,
    TxnOldCommitMapMutexOverhead = 140,
    TxnDuplicateKeyOverhead = 141,
    TxnSnapshotMutexOverhead = 142,
    TxnGetTryAgain = 143,
    NumberMultigetKeysFound = 144,
    NoIteratorCreated = 145,
    NoIteratorDeleted = 146,
    BlockCacheCompressionDictMiss = 147,
    BlockCacheCompressionDictHit = 148,
    BlockCacheCompressionDictAdd = 149,
    BlockCacheCompressionDictBytesInsert = 150,
    BlockCacheCompressionDictBytesEvict = 151,
    BlockCacheAddRedundant = 152,
    BlockCacheIndexAddRedundant = 153,
    BlockCacheFilterAddRedundant = 154,
    BlockCacheDataAddRedundant = 155,
    BlockCacheCompressionDictAddRedundant = 156,
    FilesMarkedTrash = 157,
    FilesDeletedImmediately = 158,
    ErrorHandlerBgErrorCount = 159,
    ErrorHandlerBgIoErrorCount = 160,
    ErrorHandlerBgRetryableIoErrorCount = 161,
    ErrorHandlerAutoresumeCount = 162,
    ErrorHandlerAutoresumeRetryTotalCount = 163,
    ErrorHandlerAutoresumeSuccessCount = 164,
    MemtablePayloadBytesAtFlush = 165,
    MemtableGarbageBytesAtFlush = 166,
    SecondaryCacheHits = 167,
    VerifyChecksumReadBytes = 168,
    BackupReadBytes = 169,
    BackupWriteBytes = 170,
    RemoteCompactReadBytes = 171,
    RemoteCompactWriteBytes = 172,
    HotFileReadBytes = 173,
    WarmFileReadBytes = 174,
    ColdFileReadBytes = 175,
    HotFileReadCount = 176,
    WarmFileReadCount = 177,
    ColdFileReadCount = 178,
    TitanNumGet,
    TitanNumSeek,
    TitanNumNext,
    TitanNumPrev,
    TitanBlobFileNumKeysWritten,
    TitanBlobFileNumKeysRead,
    TitanBlobFileBytesWritten,
    TitanBlobFileBytesRead,
    TitanBlobFileSynced,
    TitanGcNumFiles,
    TitanGcNumNewFiles,
    TitanGcNumKeysOverwritten,
    TitanGcNumKeysRelocated,
    TitanGcBytesOverwritten,
    TitanGcBytesRelocated,
    TitanGcBytesWritten,
    TitanGcBytesRead,
    TitanBlobCacheHit,
    TitanBlobCacheMiss,
    TitanGcNoNeed,
    TitanGcRemain,
    TitanGcDiscardable,
    TitanGcSample,
    TitanGcSmallFile,
    TitanGcFailure,
    TitanGcSuccess,
    TitanGcTriggerNext,
}
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
#[repr(u32)]
pub enum DBStatisticsHistogramType {
    DbGet = 0,
    DbWrite = 1,
    CompactionTime = 2,
    CompactionCpuTime = 3,
    SubcompactionSetupTime = 4,
    TableSyncMicros = 5,
    CompactionOutfileSyncMicros = 6,
    WalFileSyncMicros = 7,
    ManifestFileSyncMicros = 8,
    TableOpenIoMicros = 9,
    DbMultiget = 10,
    ReadBlockCompactionMicros = 11,
    ReadBlockGetMicros = 12,
    WriteRawBlockMicros = 13,
    StallL0SlowdownCount = 14,
    StallMemtableCompactionCount = 15,
    StallL0NumFilesCount = 16,
    HardRateLimitDelayCount = 17,
    SoftRateLimitDelayCount = 18,
    NumFilesInSingleCompaction = 19,
    DbSeek = 20,
    WriteStall = 21,
    SstReadMicros = 22,
    NumSubcompactionsScheduled = 23,
    BytesPerRead = 24,
    BytesPerWrite = 25,
    BytesPerMultiget = 26,
    BytesCompressed = 27,
    BytesDecompressed = 28,
    CompressionTimesNanos = 29,
    DecompressionTimesNanos = 30,
    ReadNumMergeOperands = 31,
    BlobDbKeySize = 32,
    BlobDbValueSize = 33,
    BlobDbWriteMicros = 34,
    BlobDbGetMicros = 35,
    BlobDbMultigetMicros = 36,
    BlobDbSeekMicros = 37,
    BlobDbNextMicros = 38,
    BlobDbPrevMicros = 39,
    BlobDbBlobFileWriteMicros = 40,
    BlobDbBlobFileReadMicros = 41,
    BlobDbBlobFileSyncMicros = 42,
    BlobDbGcMicros = 43,
    BlobDbCompressionMicros = 44,
    BlobDbDecompressionMicros = 45,
    FlushTime = 46,
    SstBatchSize = 47,
    DbWriteWalTime = 48,
    NumIndexAndFilterBlocksReadPerLevel = 49,
    NumDataBlocksReadPerLevel = 50,
    NumSstReadPerLevel = 51,
    ErrorHandlerAutoresumeRetryCount = 52,
    TitanKeySize,
    TitanValueSize,
    TitanGetMicros,
    TitanSeekMicros,
    TitanNextMicros,
    TitanPrevMicros,
    TitanBlobFileWriteMicros,
    TitanBlobFileReadMicros,
    TitanBlobFileSyncMicros,
    TitanManifestFileSyncMicros,
    TitanGcMicros,
    TitanGcInputFileSize,
    TitanGcOutputFileSize,
    TitanIterTouchBlobFileCount,
}
